### ISSUE TITLE
Прокрутка колесиком в поле выбранных матчей

### ISSUE THREAD

**Issue by Quazorge** [mihloruj/bethub#1]
Наводя на поле выбранных матче прокручивать их колесиком.

**Comment by mihloruj** [comment]
Добавил функцию прокрутки опций в селекте "Выбор матча для анализа". Поставил задержку в 300мс, дабы избежать ддудоса. [commit - main/static/main/js/main_table.js](https://github.com/mihloruj/bethub/commit/fc89a11ea0db32852ee9e1ffd796f37acf632351?branch=fc89a11ea0db32852ee9e1ffd796f37acf632351&diff=unified)
