### ISSUE TITLE
Удаление матчей

### ISSUE THREAD

**Issue by Quazorge** [mihloruj/bethub#3]
На странице с выбором интересующих матчей много матчей без коэфов, сразу удалять их с этой страницы что бы не мотать лишние матчи.

**Comment by mihloruj** [comment]
Теперь скрипт будет удалять матчи, которые без коэффициентов. 
[Commit - Scripts/check_next_matches.py](https://github.com/mihloruj/bethub/commit/fc89a11ea0db32852ee9e1ffd796f37acf632351?branch=fc89a11ea0db32852ee9e1ffd796f37acf632351&diff=unified)
